repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.(md|txt)$
    -   id: end-of-file-fixer
        exclude: \.(md|txt)$
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=2048']
    -   id: check-merge-conflict
        exclude: \.(md|txt)$
    -   id: check-case-conflict
        exclude: \.(md|txt)$
    -   id: mixed-line-ending
        exclude: \.(md|txt)$
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3
        exclude: \.(md|txt)$
        args: ['--line-length=128', '--indent-size=4', '--multi-line=3']

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        exclude: \.(md|txt)$
        args: ['--max-line-length=128', '--indent-size=4', '--max-complexity=3']
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
        ]

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: \.(md|txt)$
        args: ["--profile", "black", "--indent=4", "--multi-line=3"]

-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
    -   id: hadolint
        name: Lint Dockerfiles

-   repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        exclude: \.(md|txt)$
        args: [
            "--disable=C0111",  # missing-docstring
            "--disable=C0103",  # invalid-name
            "--max-branches=3"
        ]

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
    -   id: python-safety-dependencies-check
        exclude: \.(md|txt)$

-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
        name: Clear Notebook Outputs

-   repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.0.5
    hooks:
    -   id: file-contents-sorter
        name: Auto Rebase Check
        types: [text]
        args: [--ignore-case]
        stages: [rebase]
