name: fastapi-precommit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - pydantic==2.5.1
    - pre-commit==3.5.0
    - commitizen==3.12.0
    - pytest==7.4.3
    - httpx==0.25.1
    - pytest-cov==4.1.0 